[AGRICULTURE]
rice = []
millet = []
sorghum = []
silkworm = []
flour = []
dough = []
dumpling_wrapper = []
stuffing = []
dumpling = []
tea_leaf = []

[MISC]
bark = []
empty_xuan_paper = []
chinese_ink = []
charcoal_black = []
ink_stone = []
dish = ["maxStackSize(16)", "setNoRepair()"]
